services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./docker/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      # Default to 80 for production, overwrite in dev mode
      FRONTEND_PORT: ${FRONTEND_PORT:-80}

  # --- MongoDB services
  # production
  mongodb:
    profiles: ["production"]
    image: mongo:latest
    restart: unless-stopped
    networks:
      default:
        aliases:
          - mongodb_host
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}

      # Pass through for init script
      MONGO_USER_NAME: ${MONGO_USER_NAME}
      MONGO_USER_PWD: ${MONGO_USER_PWD}
    volumes:
      # Persistent data
      - mongodb_data:/data/db
      # Init script
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
  # development, exposed port
  mongodb-dev:
    profiles: ["development"]
    image: mongo:latest
    restart: unless-stopped
    networks:
      default:
        aliases:
          - mongodb_host
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}

      # Pass through for init script
      MONGO_USER_NAME: ${MONGO_USER_NAME}
      MONGO_USER_PWD: ${MONGO_USER_PWD}
    volumes:
      # Persistent data
      - mongodb_data:/data/db
      # Init script
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro

  # --- Backend (go) services
  # for production, static-build
  backend:
    profiles: ["production"]
    build:
      context: ./backend
      target: production
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      default:
        aliases:
          - backend_host
  # for development, hot-reload
  backend-dev:
    profiles: ["development"]
    build:
      context: ./backend
      target: development
    env_file:
      - .env
    depends_on:
      - mongodb-dev
    restart: unless-stopped
    volumes:
      - ./backend:/app
    networks:
      default:
        aliases:
          - backend_host

  # --- Frontend (React) services
  # for production, single-page built application
  frontend:
    profiles: ["production"]
    build: 
      context: ./frontend
      target: production
    restart: unless-stopped
    networks:
      default:
        aliases:
          - frontend_host
  # for development, hot-reload
  frontend-dev:
    profiles: ["development"]
    restart: unless-stopped
    networks:
      default:
        aliases:
          - frontend_host
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      # prevent node modules from being overwritten
      - /app/node_modules
  
volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
