x-database-template: &db-template
  image: mongo:8.2.12
  networks:
    default:
      aliases:
        - mongodb_host
  environment:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}

    # Pass through for init script
    MONGO_USER_NAME: ${MONGO_USER_NAME}
    MONGO_USER_PWD: ${MONGO_USER_PWD}
  volumes:
    # Persistent data
    - mongodb_data:/data/db
    # Init script
    - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
x-backend-template: &backend-template
  env_file:
    - .env
  networks:
    default:
      aliases:
        - backend_host
x-frontend-template: &frontend-template
  networks:
    default:
      aliases:
        - frontend_host

services:
  caddy:
    image: caddy:2.11.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./docker/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      # Default to 80 for production, overwrite in dev mode
      FRONTEND_PORT: ${FRONTEND_PORT:-80}

  # --- MongoDB services
  # production
  mongodb:
    <<: *db-template
    profiles: ["production"]
    restart: unless-stopped
  # development, exposed port
  mongodb-dev:
    <<: *db-template
    profiles: ["development"]
    ports:
      - 27017:27017

  # --- Backend (go) services
  # for production, static-build
  backend:
    <<: *backend-template
    profiles: ["production"]
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    depends_on:
      - mongodb
  # for development, hot-reload
  backend-dev:
    <<: *backend-template
    profiles: ["development"]
    build:
      context: ./backend
      target: development
    depends_on:
      - mongodb-dev
    volumes:
      - ./backend:/app

  # --- Frontend (React) services
  # for production, single-page built application
  frontend:
    <<: *frontend-template
    profiles: ["production"]
    build:
      context: ./frontend
      target: production
    restart: unless-stopped
  # for development, hot-reload
  frontend-dev:
    <<: *frontend-template
    profiles: ["development"]
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      # prevent node modules from being overwritten
      - /app/node_modules

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
